# Generated by Django 4.1.1 on 2022-09-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturls',
            name='expiration_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shorturls',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
