# Generated by Django 4.1.1 on 2022-09-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortener', '0005_alter_shorturls_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturls',
            name='expiration_day',
            field=models.IntegerField(default=30),
        ),
    ]
