# Generated by Django 4.1.1 on 2022-09-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortener', '0006_alter_shorturls_expiration_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturls',
            name='expiration_day',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
